### ISSUE TITLE
student account profile shows prompts for mentor account

### ISSUE THREAD

**Issue by kat-y** [CovEducation/CovEd#80] opened 2020-05-03 02:51 UTC
created a fake student account (not verified), when I go to edit the profile the prompts for subject and school level say:

> Please select the subjects you would like to mentor. These subjects will be listed next to your profile.
> School levels you are comfortable teaching (Optional)

Which are the prompts for mentors, not students. Might be something with using `role = "student"` in FormFields.js but `role = "mentee"` in UserProvider.js?

**Comment by oupadhyay** [comment] 2020-05-03 03:08
I think this is just something we missed. I will fix.

**Comment by oupadhyay** [comment] 2020-05-03 06:13
https://github.com/CovEducation/CovEd/blob/a1193759b16632dd7ca33597c92789f53465f4a8/client/src/components/pages/Profile.js#L152-L167
This warning should only be present for the mentors. I am not sure how to implement this, but I think you need to check if `formik.values.role === "mentor" `and if it is true, display the alert, else do not.

**Comment by sanjayyepuri** [comment] 2020-05-10 01:53
@oupadhyay That alert should stay for all users. We want parents to be aware of mentor guidelines. 

Also the main issue seems to be caused by an inconsistency in naming conventions. The `role` field of a user should be either `"student"` or `"mentor"`. 

The bug lies in `UserProvider.js`. The default role of a user is set to `"mentee"` rather than `"student"`.

https://github.com/CovEducation/CovEd/blob/fa9efba2c7a9c93af563f476ce09c3da5c234a97/client/src/providers/UserProvider.js#L24

https://github.com/CovEducation/CovEd/blob/fa9efba2c7a9c93af563f476ce09c3da5c234a97/client/src/providers/UserProvider.js#L50

**Comment by sanjayyepuri** [comment] 2020-05-13 19:53
@oupadhyay I noticed you pushed some changes to a branch. Could you submit a PR if they are ready?

**Comment by oupadhyay** [comment] 2020-05-13 20:37
I could, but I haven't tested anything yet. I think it is small enough of a change.

**Comment by sanjayyepuri** [comment] 2020-05-26 01:57
Fixed by PR #105.

**Closed by sanjayyepuri** 2020-05-26 01:57 UTC
Labels: bug, help wanted
